/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShimLayer */

#ifndef _Included_ShimLayer
#define _Included_ShimLayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShimLayer
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ShimLayer_run
  (JNIEnv *, jclass);

/*
 * Class:     ShimLayer
 * Method:    invoke
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ShimLayer_invoke
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
